#ifndef HASH_H
#define HASH_H

// Hash macros

/**
 * Defines a hash function for a given return type that computes a hash based on
 * the size of a key. Each byte in the key contributes to the hash by shifting
 * the existing hash value and adding the byte.
 *
 * @param RET_TYPE The return type of the hash function (e.g., unsigned int).
 */
#define DEF_HASH_FN_SIZED(RET_TYPE)                                            \
	RET_TYPE hash_##RET_TYPE##_sized(void *p_key, size_t len) {                \
		RET_TYPE hash = 0;                                                     \
		for (unsigned i = 0; i < len; ++i) {                                   \
			unsigned char byte = ((unsigned char *) p_key)[i];                 \
			hash = (hash << 5) + byte;                                         \
		}                                                                      \
		return hash;                                                           \
	}

/**
 * Defines a hash function for a given return type and key type. This version
 * computes the hash based on the size of a statically defined key type passed
 * as a pointer.
 *
 * @param RET_TYPE The return type of the hash function (e.g., unsigned int).
 * @param KEY_TYPE The type of the key that is being hashed.
 */
#define DEF_HASH_FN_HEAP(RET_TYPE, KEY_TYPE)                                   \
	RET_TYPE hash_##RET_TYPE##_##KEY_TYPE(void *p_key) {                       \
		RET_TYPE hash = 0;                                                     \
		for (unsigned i = 0; i < sizeof(KEY_TYPE); ++i) {                      \
			unsigned char byte = ((unsigned char *) p_key)[i];                 \
			hash = (hash << 5) + byte;                                         \
		}                                                                      \
		return hash;                                                           \
	}

/**
 * Defines a hash function for a given return type and key type. This version is
 * designed for stack-allocated keys, where the key is passed directly to the
 * function.
 *
 * @param RET_TYPE The return type of the hash function (e.g., unsigned int).
 * @param KEY_TYPE The type of the key that is being hashed.
 */
#define DEF_HASH_FN_STACK(RET_TYPE, KEY_TYPE)                                  \
	RET_TYPE hash_##RET_TYPE##_##KEY_TYPE(KEY_TYPE key) {                      \
		KEY_TYPE *p_key = &key;                                                \
		RET_TYPE  hash = 0;                                                    \
		for (unsigned i = 0; i < sizeof(KEY_TYPE); ++i) {                      \
			unsigned char byte = ((unsigned char *) p_key)[i];                 \
			hash = (hash << 5) + byte;                                         \
		}                                                                      \
		return hash;                                                           \
	}

/**
 * Defines a hash function for a given return type that computes a hash from a
 * null-terminated string. The hash is generated by processing each character in
 * the string until the terminator is reached.
 *
 * @param RET_TYPE The return type of the hash function (e.g., unsigned int).
 */
#define DEF_HASH_FN_NULLTERM(RET_TYPE)                                         \
	RET_TYPE hash_##RET_TYPE##_nullterm(const char *key) {                     \
		RET_TYPE hash = 0;                                                     \
		while (*key) {                                                         \
			hash = (hash << 5) + *key++;                                       \
		}                                                                      \
		return hash;                                                           \
	}

#endif
